# Generated by Django 5.1 on 2026-05-18 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('client', 'Client Summary'), ('order', 'Order Summary'), ('daily', 'Daily Report'), ('weekly', 'Weekly Report')], max_length=50)),
                ('content', models.TextField()),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='workspaces.workspace')),
            ],
        ),
    ]
